# Generated by Django 5.2.8 on 2025-11-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_cart_status_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paid', 'Paid (Order History)'), ('Cancelled', 'Cancelled')], default='Active', max_length=10),
        ),
    ]
