# Generated by Django 5.2.8 on 2025-11-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paid', 'Paid (Order History)')], default='Active', max_length=10),
        ),
    ]
